### ISSUE TITLE
Crash while doing /sit with CMI

### ISSUE THREAD

**Issue by RomualdYT** [jtljac/Factions#14]
https://prnt.sc/t2z19d
The server crash
Mohist 1.12.2

**Comment by jtljac** [comment]
It looks like when I add power to the player, I don't check to see if they are part of a faction, so their rank results in a null pointer
I Don't think CMI is related

**Comment by RomualdYT** [comment]
![image](https://user-images.githubusercontent.com/20307499/85180670-4ddd5700-b284-11ea-9c4b-444aaefa4782.png)
Oh hello, yes you're right! I did nothing and I crashed again
Do you have a discord ? :)
