### ISSUE TITLE
Port mod for 1.16.1

### ISSUE THREAD

**Issue by nivowski** [jtljac/Factions#20]
Can you port this mod to 1.16.1 version?

It would be much appreciated

**Comment by jtljac** [comment]
Unfortunately I'm not working with later versions of minecraft right now, I'll need to actually move to using the latest version of minecraft (I haven't moved passed 1.12 yet), and learn how to use the latest version of forge before I update any of my mods.
Anyone is welcome to fork the mod and update it themselves though, you don't need to wait for me to do it.
