### ISSUE TITLE
When will version 1.1 be ready?

### ISSUE THREAD

**Issue by javiburatos** [jtljac/Factions#27]
When will version 1.1 be ready?
I am making a server with mods and factions and this mod has turned out to be a salvation for my project since it works perfectly and is very comfortable to use. I'm waiting for your version 1.1 project to finish so I can see the new power system related commands

**Comment by jtljac** [comment]
I apologise, I don't have a date, as an alternative you could use [eagle factions](https://forums.spongepowered.org/t/eagle-factions-1-10-2-1-12-2-a-simple-yet-powerful-war-plugin/20749) which is fairly similar
It does requires sponge, which has a forge version [here](https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2).
