### ISSUE TITLE
Implement fakeplayers on/off build command

### ISSUE THREAD

**Issue by ByPaco10** [jtljac/Factions#30]
When interacting with other mods that build blocks inside your territory Factions spams this interaction the console log, if the mod would have a command for fakeplayer building on/off, this console spam problem would be resolved

**Comment by jtljac** [comment]
That's my bad, I left that log mainly in for my own debug's sake, I've removed logging that in the latest commit (adaf93b8cb8bde07f392b540c63f43fefbaff8c7)
